/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | init ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("disengaged") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | disengaged")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleLoad",cond=whenRequest("requestToLoad"))
				}	 
				state("handleLoad") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("requestToLoad(NOARGS)"), Term.createTerm("requestToLoad(NOARGS)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								        	var r = "1"
								if(  r == "1"  
								 ){CommUtils.outmagenta("$name | load: succesfull")
								CommUtils.outmagenta("$name | load: engaged")
								answer("requestToLoad", "loadAnswer", "loadAnswer(slot2)"   )  
								delay(5000) 
								}
								if(  r == "2"  
								 ){CommUtils.outmagenta("$name | load: retry later")
								answer("requestToLoad", "loadAnswer", "loadAnswer(retrylater)"   )  
								}
								if(  r == "3"  
								 ){CommUtils.outmagenta("$name | load: rejected")
								answer("requestToLoad", "loadAnswer", "loadAnswer(rejected)"   )  
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
			}
		}
} 
